repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: no-commit-to-branch
  
  - repo: local
    hooks:
      - id: lint with ruff
        name: Lint with Ruff
        entry: ruff check .
        types: [python]
        language: system
        pass_filenames: false
      - id: typecheck with pyright
        name: Typecheck with Pyright
        entry: uv run pyright
        types: [python]
        language: system
        pass_filenames: false
      - id: typecheck with mypy
        name: Typecheck with Mypy
        entry: uv run mypy ./src ./tests
        types: [python]
        language: system
        pass_filenames: false
        